### ISSUE TITLE
token logger

### ISSUE THREAD

**Issue by Tomirocks7** [NotTiie/XTool#1]
dont download this shit got hacked and it sends a download to everyone in dms with a token logger saying its a spoofer

**Comment by NotTiie** [comment]
> dont download this shit got hacked and it sends a download to everyone in dms with a token logger saying its a spoofer

It's literally open source lmao + cope

**Comment by logicguy1** [comment]
Well yes but actually no, there are a few exe files dotted around

**Comment by NotTiie** [comment]
It's not my responsibility, I tested the tools and they worked for me. If you are afraid to use them, don't use them.
